// Mock data para funcionários
export const mockEmployees = [
  {
    id: 'emp-1',
    name: 'Carlos Silva',
    email: 'carlos.silva@vigiasystem.com',
    role: 'guard',
    phone: '(11) 98765-4321',
    cpf: '123.456.789-00',
    address: 'Rua das Acácias, 123 - São Paulo, SP',
    status: 'active',
    assignedRoutes: ['route-1', 'route-4'],
    createdAt: '2024-01-15',
  },
  {
    id: 'emp-2',
    name: 'Maria Santos',
    email: 'maria.santos@vigiasystem.com',
    role: 'guard',
    phone: '(11) 98765-4322',
    cpf: '123.456.789-01',
    address: 'Av. Paulista, 456 - São Paulo, SP',
    status: 'active',
    assignedRoutes: [],
    createdAt: '2024-01-20',
  },
  {
    id: 'emp-3',
    name: 'João Oliveira',
    email: 'joao.oliveira@vigiasystem.com',
    role: 'guard',
    phone: '(11) 98765-4323',
    cpf: '123.456.789-02',
    address: 'Rua dos Pinheiros, 789 - São Paulo, SP',
    status: 'active',
    assignedRoutes: ['route-2'],
    createdAt: '2024-02-01',
  },
  {
    id: 'emp-4',
    name: 'Ana Costa',
    email: 'ana.costa@vigiasystem.com',
    role: 'guard',
    phone: '(11) 98765-4324',
    cpf: '123.456.789-03',
    address: 'Rua Augusta, 321 - São Paulo, SP',
    status: 'inactive',
    assignedRoutes: [],
    createdAt: '2024-02-10',
  },
  {
    id: 'emp-5',
    name: 'Roberto Ferreira',
    email: 'roberto.ferreira@vigiasystem.com',
    role: 'supervisor',
    phone: '(11) 98765-4325',
    cpf: '123.456.789-04',
    address: 'Av. Faria Lima, 654 - São Paulo, SP',
    status: 'active',
    assignedRoutes: ['route-3'],
    createdAt: '2024-02-15',
  },
];

// Mock data para estabelecimentos
export const mockEstablishments = [
  {
    id: 'est-1',
    name: 'Shopping Center Plaza',
    type: 'shopping',
    address: 'Av. Paulista, 1000 - São Paulo, SP',
    phone: '(11) 3000-1000',
    contactPerson: 'Pedro Almeida',
    activeRoutes: 1,
    totalRoutes: 1,
    status: 'active',
    createdAt: '2024-01-10',
  },
  {
    id: 'est-2',
    name: 'Condomínio Residencial Vista Verde',
    type: 'condominium',
    address: 'Rua das Flores, 500 - São Paulo, SP',
    phone: '(11) 3000-2000',
    contactPerson: 'Juliana Mendes',
    activeRoutes: 1,
    totalRoutes: 1,
    status: 'active',
    createdAt: '2024-01-15',
  },
  {
    id: 'est-3',
    name: 'Fábrica Industrial TechParts',
    type: 'factory',
    address: 'Rodovia dos Bandeirantes, km 25 - São Paulo, SP',
    phone: '(11) 3000-3000',
    contactPerson: 'Ricardo Souza',
    activeRoutes: 1,
    totalRoutes: 1,
    status: 'active',
    createdAt: '2024-01-20',
  },
  {
    id: 'est-4',
    name: 'Hospital São Lucas',
    type: 'hospital',
    address: 'Av. Rebouças, 2000 - São Paulo, SP',
    phone: '(11) 3000-4000',
    contactPerson: 'Dr. Fernando Lima',
    activeRoutes: 1,
    totalRoutes: 1,
    status: 'active',
    createdAt: '2024-01-25',
  },
];

// Mock data para rotas
export const mockRoutes = [
  {
    id: 'route-1',
    name: 'Ronda Noturna Shopping - Perímetro',
    establishmentId: 'est-1',
    establishmentName: 'Shopping Center Plaza',
    type: 'external',
    frequency: 'daily',
    status: 'active',
    assignedGuards: ['emp-1', 'emp-2', 'emp-3'],
    assignedGuardsNames: ['Carlos Silva', 'Maria Santos', 'João Oliveira'],
    createdAt: '2024-02-01',
    schedule: {
      startTime: '22:00',
      endTime: '06:00',
      allowedDays: [0, 1, 2, 3, 4, 5, 6], // Todos os dias
    },
    points: [
      { id: 'point-1-1', name: 'Portaria Principal', type: 'qrcode', order: 1, latitude: -23.5505, longitude: -46.6333 },
      { id: 'point-1-2', name: 'Estacionamento Subsolo 1', type: 'qrcode', order: 2, latitude: -23.5505, longitude: -46.6333 },
      { id: 'point-1-3', name: 'Estacionamento Subsolo 2', type: 'qrcode', order: 3, latitude: -23.5506, longitude: -46.6334 },
      { id: 'point-1-4', name: 'Saída de Emergência Leste', type: 'qrcode', order: 4, latitude: -23.5507, longitude: -46.6335 },
      { id: 'point-1-5', name: 'Saída de Emergência Oeste', type: 'qrcode', order: 5, latitude: -23.5508, longitude: -46.6336 },
      { id: 'point-1-6', name: 'Terraço - Vista Geral', type: 'photo', order: 6, latitude: -23.5509, longitude: -46.6337 },
      { id: 'point-1-7', name: 'Central de Segurança', type: 'qrcode', order: 7, latitude: -23.5510, longitude: -46.6338 },
    ],
  },
  {
    id: 'route-2',
    name: 'Ronda Diurna Condomínio - Blocos A, B e C',
    establishmentId: 'est-2',
    establishmentName: 'Condomínio Residencial Vista Verde',
    type: 'internal',
    frequency: 'daily',
    status: 'active',
    assignedGuards: ['emp-1', 'emp-3'],
    assignedGuardsNames: ['Carlos Silva', 'João Oliveira'],
    createdAt: '2024-02-05',
    schedule: {
      startTime: '08:00',
      endTime: '18:00',
      allowedDays: [1, 2, 3, 4, 5], // Segunda a sexta
    },
    points: [
      { id: 'point-2-1', name: 'Portaria Social', type: 'qrcode', order: 1, latitude: -23.5615, longitude: -46.6562 },
      { id: 'point-2-2', name: 'Bloco A - Térreo', type: 'qrcode', order: 2, latitude: -23.5615, longitude: -46.6562 },
      { id: 'point-2-3', name: 'Bloco B - Térreo', type: 'qrcode', order: 3, latitude: -23.5616, longitude: -46.6563 },
      { id: 'point-2-4', name: 'Bloco C - Térreo', type: 'qrcode', order: 4, latitude: -23.5617, longitude: -46.6564 },
      { id: 'point-2-5', name: 'Área de Lazer', type: 'photo', order: 5, latitude: -23.5618, longitude: -46.6565 },
      { id: 'point-2-6', name: 'Playground', type: 'photo', order: 6, latitude: -23.5619, longitude: -46.6566 },
      { id: 'point-2-7', name: 'Academia', type: 'qrcode', order: 7, latitude: -23.5620, longitude: -46.6567 },
      { id: 'point-2-8', name: 'Piscina', type: 'photo', order: 8, latitude: -23.5621, longitude: -46.6568 },
      { id: 'point-2-9', name: 'Guarita de Fundos', type: 'qrcode', order: 9, latitude: -23.5622, longitude: -46.6569 },
    ],
  },
  {
    id: 'route-3',
    name: 'Supervisão Fábrica - Galpões 1 a 4',
    establishmentId: 'est-3',
    establishmentName: 'Fábrica Industrial TechParts',
    type: 'supervision',
    frequency: 'daily',
    status: 'active',
    assignedGuards: ['emp-5'],
    assignedGuardsNames: ['Roberto Ferreira'],
    createdAt: '2024-02-10',
    schedule: {
      startTime: '06:00',
      endTime: '22:00',
      allowedDays: [1, 2, 3, 4, 5], // Segunda a sexta
    },
    points: [
      { id: 'point-3-1', name: 'Guarita de Entrada', type: 'qrcode', order: 1, latitude: -23.5320, longitude: -46.7916 },
      { id: 'point-3-2', name: 'Galpão 1 - Produção', type: 'qrcode', order: 2, latitude: -23.5320, longitude: -46.7916 },
      { id: 'point-3-3', name: 'Galpão 2 - Montagem', type: 'qrcode', order: 3, latitude: -23.5321, longitude: -46.7917 },
      { id: 'point-3-4', name: 'Galpão 3 - Estoque', type: 'photo', order: 4, latitude: -23.5322, longitude: -46.7918 },
      { id: 'point-3-5', name: 'Galpão 4 - Expedição', type: 'photo', order: 5, latitude: -23.5323, longitude: -46.7919 },
      { id: 'point-3-6', name: 'Sala de Controle', type: 'qrcode', order: 6, latitude: -23.5324, longitude: -46.7920 },
      { id: 'point-3-7', name: 'Pátio de Caminhões', type: 'photo', order: 7, latitude: -23.5325, longitude: -46.7921 },
      { id: 'point-3-8', name: 'Geradores', type: 'photo', order: 8, latitude: -23.5326, longitude: -46.7922 },
      { id: 'point-3-9', name: 'Subestação Elétrica', type: 'qrcode', order: 9, latitude: -23.5327, longitude: -46.7923 },
      { id: 'point-3-10', name: 'Portão de Saída', type: 'qrcode', order: 10, latitude: -23.5328, longitude: -46.7924 },
    ],
  },
  {
    id: 'route-4',
    name: 'Ronda Hospital - Andares e Emergências',
    establishmentId: 'est-4',
    establishmentName: 'Hospital São Lucas',
    type: 'internal',
    frequency: 'daily',
    status: 'active',
    assignedGuards: ['emp-1'],
    assignedGuardsNames: ['Carlos Silva'],
    createdAt: '2024-02-15',
    schedule: {
      startTime: '00:00',
      endTime: '23:59',
      allowedDays: [0, 1, 2, 3, 4, 5, 6], // 24/7
    },
    points: [
      { id: 'point-4-1', name: 'Recepção Principal', type: 'qrcode', order: 1, latitude: -23.5500, longitude: -46.6340 },
      { id: 'point-4-2', name: 'Pronto Socorro', type: 'qrcode', order: 2, latitude: -23.5500, longitude: -46.6340 },
      { id: 'point-4-3', name: 'Centro Cirúrgico - 2º Andar', type: 'qrcode', order: 3, latitude: -23.5501, longitude: -46.6341 },
      { id: 'point-4-4', name: 'UTI - 3º Andar', type: 'qrcode', order: 4, latitude: -23.5502, longitude: -46.6342 },
      { id: 'point-4-5', name: 'Internação - 4º Andar', type: 'photo', order: 5, latitude: -23.5501, longitude: -46.6341 },
      { id: 'point-4-6', name: 'Farmácia Central', type: 'qrcode', order: 6, latitude: -23.5503, longitude: -46.6343 },
      { id: 'point-4-7', name: 'Estacionamento Funcionários', type: 'photo', order: 7, latitude: -23.5504, longitude: -46.6344 },
      { id: 'point-4-8', name: 'Almoxarifado', type: 'qrcode', order: 8, latitude: -23.5505, longitude: -46.6345 },
      { id: 'point-4-9', name: 'Saída de Emergência - Ala Norte', type: 'qrcode', order: 9, latitude: -23.5502, longitude: -46.6342 },
      { id: 'point-4-10', name: 'Saída de Emergência - Ala Sul', type: 'qrcode', order: 10, latitude: -23.5503, longitude: -46.6343 },
      { id: 'point-4-11', name: 'Central de Segurança', type: 'qrcode', order: 11, latitude: -23.5506, longitude: -46.6346 },
      { id: 'point-4-12', name: 'Heliponto', type: 'photo', order: 12, latitude: -23.5507, longitude: -46.6347 },
    ],
  },
];

// Mock data para pontos de rota (array flat)
export const mockRoutePointsFlat = mockRoutes.flatMap(route => 
  route.points.map(point => ({
    ...point,
    routeId: route.id,
    routeName: route.name,
  }))
);

// Mock data para pontos de rota (indexado por routeId)
export const mockRoutePoints: Record<string, any[]> = {
  'route-1': mockRoutes[0].points.map(p => ({ ...p, qrCode: `QR-${p.id}`, verified: false })),
  'route-2': mockRoutes[1].points.map(p => ({ ...p, qrCode: `QR-${p.id}`, verified: false })),
  'route-3': mockRoutes[2].points.map(p => ({ ...p, qrCode: `QR-${p.id}`, verified: false })),
  'route-4': mockRoutes[3].points.map(p => ({ ...p, qrCode: `QR-${p.id}`, verified: false })),
};

// Mock data para ocorrências
export const mockOccurrences = [
  {
    id: 'occ-1',
    type: 'Atividade Suspeita',
    severity: 'high',
    status: 'resolved',
    description: 'Indivíduo não identificado tentando acesso pela área de serviço',
    location: 'Shopping Center Plaza - Entrada de Serviço',
    guardId: 'emp-1',
    guardName: 'Carlos Silva',
    timestamp: '2024-11-13T23:45:00Z',
    resolvedAt: '2024-11-14T00:15:00Z',
    attachments: [],
  },
  {
    id: 'occ-2',
    type: 'Dano ao Patrimônio',
    severity: 'medium',
    status: 'pending',
    description: 'Vidro quebrado na porta do bloco B',
    location: 'Condomínio Residencial Vista Verde - Bloco B',
    guardId: 'emp-3',
    guardName: 'João Oliveira',
    timestamp: '2024-11-14T08:30:00Z',
    resolvedAt: null,
    attachments: [],
  },
  {
    id: 'occ-3',
    type: 'Emergência Médica',
    severity: 'critical',
    status: 'resolved',
    description: 'Paciente em situação crítica, SAMU acionado',
    location: 'Hospital São Lucas - UTI',
    guardId: 'emp-1',
    guardName: 'Carlos Silva',
    timestamp: '2024-11-14T03:20:00Z',
    resolvedAt: '2024-11-14T03:45:00Z',
    attachments: [],
  },
];

// Mock data para mensagens do chat
export const mockChatMessages = [
  {
    id: 'msg-1',
    senderId: 'emp-1',
    senderName: 'Carlos Silva',
    content: 'Boa noite, pessoal! Iniciando ronda noturna no Shopping.',
    timestamp: '2024-11-13T22:00:00Z',
    read: true,
  },
  {
    id: 'msg-2',
    senderId: 'emp-3',
    senderName: 'João Oliveira',
    content: 'Bom dia! Tudo tranquilo na ronda diurna do condomínio.',
    timestamp: '2024-11-14T08:00:00Z',
    read: true,
  },
  {
    id: 'msg-3',
    senderId: 'emp-5',
    senderName: 'Roberto Ferreira',
    content: 'Pessoal, identifiquei uma porta destrancada no Galpão 3. Já providenciei o fechamento.',
    timestamp: '2024-11-13T19:25:00Z',
    read: true,
  },
  {
    id: 'msg-4',
    senderId: 'emp-1',
    senderName: 'Carlos Silva',
    content: 'Atenção! Alarme defeituoso na saída de emergência da Ala Norte do hospital. Manutenção acionada.',
    timestamp: '2024-11-14T04:12:00Z',
    read: false,
  },
];

// Mock data para relatórios de rondas executadas
export const mockRoundReports = [
  {
    id: 'report-1',
    routeId: 'route-1',
    routeName: 'Ronda Noturna Shopping - Perímetro',
    establishmentName: 'Shopping Center Plaza',
    guardId: 'emp-1',
    guardName: 'Carlos Silva',
    startTime: '2024-11-13T22:15:00Z',
    endTime: '2024-11-13T23:48:00Z',
    duration: 93, // minutos
    status: 'completed',
    pointsChecked: [
      {
        pointId: 'point-1-1',
        pointName: 'Portaria Principal',
        type: 'qrcode',
        checkedAt: '2024-11-13T22:15:00Z',
        status: 'success',
        latitude: -23.5505,
        longitude: -46.6333,
      },
      {
        pointId: 'point-1-2',
        pointName: 'Estacionamento Subsolo 1',
        type: 'qrcode',
        checkedAt: '2024-11-13T22:28:00Z',
        status: 'success',
        latitude: -23.5505,
        longitude: -46.6333,
      },
      {
        pointId: 'point-1-3',
        pointName: 'Estacionamento Subsolo 2',
        type: 'qrcode',
        checkedAt: '2024-11-13T22:41:00Z',
        status: 'success',
        latitude: -23.5506,
        longitude: -46.6334,
      },
      {
        pointId: 'point-1-4',
        pointName: 'Saída de Emergência Leste',
        type: 'qrcode',
        checkedAt: '2024-11-13T22:58:00Z',
        status: 'success',
        latitude: -23.5507,
        longitude: -46.6335,
      },
      {
        pointId: 'point-1-5',
        pointName: 'Saída de Emergência Oeste',
        type: 'qrcode',
        checkedAt: '2024-11-13T23:12:00Z',
        status: 'success',
        latitude: -23.5508,
        longitude: -46.6336,
      },
      {
        pointId: 'point-1-6',
        pointName: 'Terraço - Vista Geral',
        type: 'photo',
        checkedAt: '2024-11-13T23:29:00Z',
        status: 'success',
        photoUrl: 'https://images.unsplash.com/photo-1555636222-cae831e670b3',
        latitude: -23.5509,
        longitude: -46.6337,
      },
      {
        pointId: 'point-1-7',
        pointName: 'Central de Segurança',
        type: 'qrcode',
        checkedAt: '2024-11-13T23:48:00Z',
        status: 'success',
        latitude: -23.5510,
        longitude: -46.6338,
      },
    ],
    occurrences: [
      {
        id: 'occ-report-1',
        type: 'Atividade Suspeita',
        severity: 'high',
        description: 'Indivíduo não identificado circulando no estacionamento subsolo 1. Abordagem realizada, pessoa estava aguardando motorista de aplicativo.',
        location: 'Estacionamento Subsolo 1',
        timestamp: '2024-11-13T22:30:00Z',
        resolved: true,
      }
    ],
    notes: 'Ronda realizada conforme planejado. Uma ocorrência de atividade suspeita foi identificada e resolvida. Todos os pontos verificados com sucesso.',
    completionRate: 100,
  },
  {
    id: 'report-2',
    routeId: 'route-2',
    routeName: 'Ronda Diurna Condomínio - Blocos A, B e C',
    establishmentName: 'Condomínio Residencial Vista Verde',
    guardId: 'emp-3',
    guardName: 'João Oliveira',
    startTime: '2024-11-14T08:00:00Z',
    endTime: '2024-11-14T10:25:00Z',
    duration: 145, // minutos
    status: 'completed',
    pointsChecked: [
      {
        pointId: 'point-2-1',
        pointName: 'Portaria Social',
        type: 'qrcode',
        checkedAt: '2024-11-14T08:00:00Z',
        status: 'success',
        latitude: -23.5615,
        longitude: -46.6562,
      },
      {
        pointId: 'point-2-2',
        pointName: 'Bloco A - Térreo',
        type: 'geolocation',
        checkedAt: '2024-11-14T08:18:00Z',
        status: 'success',
        latitude: -23.5615,
        longitude: -46.6562,
      },
      {
        pointId: 'point-2-3',
        pointName: 'Bloco B - Térreo',
        type: 'geolocation',
        checkedAt: '2024-11-14T08:35:00Z',
        status: 'success',
        latitude: -23.5616,
        longitude: -46.6563,
      },
      {
        pointId: 'point-2-4',
        pointName: 'Bloco C - Térreo',
        type: 'geolocation',
        checkedAt: '2024-11-14T08:52:00Z',
        status: 'success',
        latitude: -23.5617,
        longitude: -46.6564,
      },
      {
        pointId: 'point-2-5',
        pointName: 'Área de Lazer',
        type: 'photo',
        checkedAt: '2024-11-14T09:10:00Z',
        status: 'success',
        photoUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c',
        latitude: -23.5618,
        longitude: -46.6565,
      },
      {
        pointId: 'point-2-6',
        pointName: 'Playground',
        type: 'photo',
        checkedAt: '2024-11-14T09:28:00Z',
        status: 'success',
        photoUrl: 'https://images.unsplash.com/photo-1587582423116-ec07293f0395',
        latitude: -23.5619,
        longitude: -46.6566,
      },
      {
        pointId: 'point-2-7',
        pointName: 'Academia',
        type: 'qrcode',
        checkedAt: '2024-11-14T09:48:00Z',
        status: 'success',
        latitude: -23.5620,
        longitude: -46.6567,
      },
      {
        pointId: 'point-2-8',
        pointName: 'Piscina',
        type: 'photo',
        checkedAt: '2024-11-14T10:05:00Z',
        status: 'success',
        photoUrl: 'https://images.unsplash.com/photo-1576013551627-0cc20b96c2a7',
        latitude: -23.5621,
        longitude: -46.6568,
      },
      {
        pointId: 'point-2-9',
        pointName: 'Guarita de Fundos',
        type: 'qrcode',
        checkedAt: '2024-11-14T10:25:00Z',
        status: 'success',
        latitude: -23.5622,
        longitude: -46.6569,
      },
    ],
    occurrences: [
      {
        id: 'occ-report-2',
        type: 'Dano ao Patrimônio',
        severity: 'medium',
        description: 'Vidro da porta de entrada do Bloco B encontrado com pequena rachadura. Síndico foi notificado para providenciar reparo.',
        location: 'Bloco B - Térreo',
        timestamp: '2024-11-14T08:37:00Z',
        resolved: false,
      }
    ],
    notes: 'Ronda concluída com sucesso. Identificado dano ao patrimônio no Bloco B. Todas as áreas comuns verificadas e em ordem.',
    completionRate: 100,
  },
  {
    id: 'report-3',
    routeId: 'route-3',
    routeName: 'Supervisão Fábrica - Galpões 1 a 4',
    establishmentName: 'Fábrica Industrial TechParts',
    guardId: 'emp-5',
    guardName: 'Roberto Ferreira',
    startTime: '2024-11-13T18:30:00Z',
    endTime: '2024-11-13T20:55:00Z',
    duration: 145, // minutos
    status: 'completed',
    pointsChecked: [
      {
        pointId: 'point-3-1',
        pointName: 'Guarita de Entrada',
        type: 'qrcode',
        checkedAt: '2024-11-13T18:30:00Z',
        status: 'success',
        latitude: -23.5320,
        longitude: -46.7916,
      },
      {
        pointId: 'point-3-2',
        pointName: 'Galpão 1 - Produção',
        type: 'geolocation',
        checkedAt: '2024-11-13T18:45:00Z',
        status: 'success',
        latitude: -23.5320,
        longitude: -46.7916,
      },
      {
        pointId: 'point-3-3',
        pointName: 'Galpão 2 - Montagem',
        type: 'geolocation',
        checkedAt: '2024-11-13T19:02:00Z',
        status: 'success',
        latitude: -23.5321,
        longitude: -46.7917,
      },
      {
        pointId: 'point-3-4',
        pointName: 'Galpão 3 - Estoque',
        type: 'geolocation',
        checkedAt: '2024-11-13T19:18:00Z',
        status: 'success',
        latitude: -23.5322,
        longitude: -46.7918,
      },
      {
        pointId: 'point-3-5',
        pointName: 'Galpão 4 - Expedição',
        type: 'geolocation',
        checkedAt: '2024-11-13T19:35:00Z',
        status: 'success',
        latitude: -23.5323,
        longitude: -46.7919,
      },
      {
        pointId: 'point-3-6',
        pointName: 'Sala de Controle',
        type: 'qrcode',
        checkedAt: '2024-11-13T19:52:00Z',
        status: 'success',
        latitude: -23.5324,
        longitude: -46.7920,
      },
      {
        pointId: 'point-3-7',
        pointName: 'Pátio de Caminhões',
        type: 'photo',
        checkedAt: '2024-11-13T20:10:00Z',
        status: 'success',
        photoUrl: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d',
        latitude: -23.5325,
        longitude: -46.7921,
      },
      {
        pointId: 'point-3-8',
        pointName: 'Geradores',
        type: 'photo',
        checkedAt: '2024-11-13T20:28:00Z',
        status: 'success',
        photoUrl: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837',
        latitude: -23.5326,
        longitude: -46.7922,
      },
      {
        pointId: 'point-3-9',
        pointName: 'Subestação Elétrica',
        type: 'qrcode',
        checkedAt: '2024-11-13T20:42:00Z',
        status: 'success',
        latitude: -23.5327,
        longitude: -46.7923,
      },
      {
        pointId: 'point-3-10',
        pointName: 'Portão de Saída',
        type: 'qrcode',
        checkedAt: '2024-11-13T20:55:00Z',
        status: 'success',
        latitude: -23.5328,
        longitude: -46.7924,
      },
    ],
    occurrences: [
      {
        id: 'occ-report-3',
        type: 'Falha Operacional',
        severity: 'high',
        description: 'Porta do Galpão 3 encontrada destrancada. Área foi verificada, nenhuma irregularidade detectada. Porta foi trancada e supervisor de turno foi notificado.',
        location: 'Galpão 3 - Estoque',
        timestamp: '2024-11-13T19:20:00Z',
        resolved: true,
      },
      {
        id: 'occ-report-3b',
        type: 'Manutenção',
        severity: 'low',
        description: 'Lâmpada queimada no pátio de caminhões próximo ao portão 2. Manutenção já foi acionada.',
        location: 'Pátio de Caminhões',
        timestamp: '2024-11-13T20:12:00Z',
        resolved: false,
      }
    ],
    notes: 'Supervisão realizada com atenção. Duas ocorrências identificadas: porta destrancada (resolvida) e lâmpada queimada (manutenção acionada). Perímetro seguro.',
    completionRate: 100,
  },
  {
    id: 'report-4',
    routeId: 'route-4',
    routeName: 'Ronda Hospital - Andares e Emergências',
    establishmentName: 'Hospital São Lucas',
    guardId: 'emp-1',
    guardName: 'Carlos Silva',
    startTime: '2024-11-14T02:00:00Z',
    endTime: '2024-11-14T04:52:00Z',
    duration: 172, // minutos
    status: 'completed_with_issues',
    pointsChecked: [
      {
        pointId: 'point-4-1',
        pointName: 'Recepção Principal',
        type: 'qrcode',
        checkedAt: '2024-11-14T02:00:00Z',
        status: 'success',
        latitude: -23.5500,
        longitude: -46.6340,
      },
      {
        pointId: 'point-4-2',
        pointName: 'Pronto Socorro',
        type: 'geolocation',
        checkedAt: '2024-11-14T02:15:00Z',
        status: 'success',
        latitude: -23.5500,
        longitude: -46.6340,
      },
      {
        pointId: 'point-4-3',
        pointName: 'Centro Cirúrgico - 2º Andar',
        type: 'qrcode',
        checkedAt: '2024-11-14T02:32:00Z',
        status: 'success',
        latitude: -23.5501,
        longitude: -46.6341,
      },
      {
        pointId: 'point-4-4',
        pointName: 'UTI - 3º Andar',
        type: 'qrcode',
        checkedAt: '2024-11-14T02:48:00Z',
        status: 'success',
        latitude: -23.5502,
        longitude: -46.6342,
      },
      {
        pointId: 'point-4-5',
        pointName: 'Internação - 4º Andar',
        type: 'geolocation',
        checkedAt: '2024-11-14T03:05:00Z',
        status: 'success',
        latitude: -23.5501,
        longitude: -46.6341,
      },
      {
        pointId: 'point-4-6',
        pointName: 'Farmácia Central',
        type: 'qrcode',
        checkedAt: '2024-11-14T03:22:00Z',
        status: 'success',
        latitude: -23.5503,
        longitude: -46.6343,
      },
      {
        pointId: 'point-4-7',
        pointName: 'Estacionamento Funcionários',
        type: 'photo',
        checkedAt: '2024-11-14T03:38:00Z',
        status: 'success',
        photoUrl: 'https://images.unsplash.com/photo-1590674899484-d5640e854abe',
        latitude: -23.5504,
        longitude: -46.6344,
      },
      {
        pointId: 'point-4-8',
        pointName: 'Almoxarifado',
        type: 'qrcode',
        checkedAt: '2024-11-14T03:55:00Z',
        status: 'success',
        latitude: -23.5505,
        longitude: -46.6345,
      },
      {
        pointId: 'point-4-9',
        pointName: 'Saída de Emergência - Ala Norte',
        type: 'geolocation',
        checkedAt: '2024-11-14T04:10:00Z',
        status: 'failed',
        note: 'Porta de emergência com alarme defeituoso - não foi possível verificar',
        latitude: -23.5502,
        longitude: -46.6342,
      },
      {
        pointId: 'point-4-10',
        pointName: 'Saída de Emergência - Ala Sul',
        type: 'geolocation',
        checkedAt: '2024-11-14T04:25:00Z',
        status: 'success',
        latitude: -23.5503,
        longitude: -46.6343,
      },
      {
        pointId: 'point-4-11',
        pointName: 'Central de Segurança',
        type: 'qrcode',
        checkedAt: '2024-11-14T04:40:00Z',
        status: 'success',
        latitude: -23.5506,
        longitude: -46.6346,
      },
      {
        pointId: 'point-4-12',
        pointName: 'Heliponto',
        type: 'photo',
        checkedAt: '2024-11-14T04:52:00Z',
        status: 'success',
        photoUrl: 'https://images.unsplash.com/photo-1587351021759-3e566b6af7cc',
        latitude: -23.5507,
        longitude: -46.6347,
      },
    ],
    occurrences: [
      {
        id: 'occ-report-4',
        type: 'Falha de Equipamento',
        severity: 'high',
        description: 'Alarme da porta de emergência da Ala Norte apresentando defeito. Não dispara ao abrir a porta. Manutenção emergencial foi acionada.',
        location: 'Saída de Emergência - Ala Norte',
        timestamp: '2024-11-14T04:11:00Z',
        resolved: false,
      },
      {
        id: 'occ-report-4b',
        type: 'Acesso Não Autorizado',
        severity: 'medium',
        description: 'Pessoa dormindo no banco do estacionamento de funcionários. Abordagem realizada, tratava-se de familiar de paciente aguardando visitação. Orientado sobre local adequado de espera.',
        location: 'Estacionamento Funcionários',
        timestamp: '2024-11-14T03:40:00Z',
        resolved: true,
      }
    ],
    notes: 'Ronda realizada com 2 ocorrências. ATENÇÃO: Alarme de emergência da Ala Norte com defeito crítico - manutenção emergencial acionada. 11 de 12 pontos verificados com sucesso (91.67%).',
    completionRate: 91.67,
  },
];

// Função para obter estatísticas de relatórios
export function getReportStats() {
  const total = mockRoundReports.length;
  const completed = mockRoundReports.filter(r => r.status === 'completed').length;
  const withIssues = mockRoundReports.filter(r => r.status === 'completed_with_issues').length;
  const totalOccurrences = mockRoundReports.reduce((acc, r) => acc + r.occurrences.length, 0);
  const avgCompletionRate = mockRoundReports.reduce((acc, r) => acc + r.completionRate, 0) / total;
  const avgDuration = mockRoundReports.reduce((acc, r) => acc + r.duration, 0) / total;

  return {
    total,
    completed,
    withIssues,
    totalOccurrences,
    avgCompletionRate: avgCompletionRate.toFixed(1),
    avgDuration: Math.round(avgDuration),
  };
}

// Função para obter nome do funcionário por ID
export function getEmployeeName(employeeId: string): string {
  const employee = mockEmployees.find(emp => emp.id === employeeId);
  return employee ? employee.name : 'Desconhecido';
}